volumes:
  postgres_data:
    driver: local

services:
  app:
    stop_grace_period: 1s
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    expose:
      - "8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=default
      - POSTGRES_USER=default
      - POSTGRES_PASSWORD=secret
    networks:
      - main-network

networks:
  main-network:
    driver: bridge